name: e_kas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies: 
  flutter:
    sdk: flutter
  lottie: ^3.1.2
  http: ^1.2.1
  flutter_bloc: ^8.1.6
  jwt_decoder: ^2.0.1
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.0.6
  flutter_secure_storage: ^8.0.0
  fl_chart: ^0.68.0
  file_picker: ^8.0.6
  intl: ^0.19.0
  http_parser: ^4.0.2
  url_launcher: ^6.3.0
  path_provider: ^2.0.10



dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/animations/lottie_animation.json
    - assets/image/
    - .env
